plugins:
  # https://github.com/babel/eslint-plugin-babel
  - babel
env:
  browser: true
  es6: true
  node: true
# https://github.com/babel/babel-eslint
parser: babel-eslint

extends:
  - 'airbnb-base'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}