plugins:
  - jest
  - babel
env:
  browser: true
  es6: true
  node: true

parser: babel-eslint

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: {}